### PR TITLE
BY-COVID end of project

### PR DESCRIPTION
**Pull request by wm75**

### CODE REVIEW

**Review by bgruening — APPROVED** [review]
Schon super! Aber ich hätte gerne auch einen Blog post ;)

**Comment by wm75** [comment]
Coming in https://github.com/galaxyproject/galaxy-hub/pull/2760 :-)

Will change the posts here to link to it.

**Comment by wm75** [comment]
@bgruening like this maybe?

**Comment by bgruening** [comment]
I think so. I'm still not a fan of threads I guess, or many threads.
I tend to think that all plugins that have a small character limit should go into a separate file. So that we can tweak those without interfering with the longer posts.

**Review by bgruening — APPROVED** [review]

**Pull request merged**
