### PR TITLE
Combine workflows for creating preview and publishing content into one workflow

### PR DESCRIPTION
**Pull request by arash77**
This PR combines the workflows for creating preview and publishing content into one workflow.

### CODE REVIEW

**Review by bgruening — APPROVED** [review]
looks ok to me!

**Comment by arash77** [comment]
This also covers #36

**Review by wm75 — COMMENTED** [review]
Wouldn't this be a use case for [composite actions](https://docs.github.com/en/actions/creating-actions/creating-a-composite-action) to make the env and branch setup reusable across the two existing workflows?

Would seem like the cleaner approach to me that would allow for the two workflows to diverge more in the future.

**Comment by arash77** [comment]
Thank you @wm75, Using composite actions seems to be a better idea. I will later work on that.

**Comment by arash77** [comment]
I will then close this PR to work on that approach soon.

**Pull request closed without merging**
