### PR TITLE
add small link to create new files

### PR DESCRIPTION
**Pull request by bgruening**

### CODE REVIEW

**Comment by arash77** [comment]
Should this link redirect to the main branch?

**Comment by bgruening** [comment]
Is it not?

**Comment by arash77** [comment]
Yes, it is but if someone wants to create a pr shouldn't it create a new post file in another branch?

**Comment by bgruening** [comment]
Probably ... we can close that. BUT, a few core people will most likely not work on the commandline. So that would be the easiest way.

You are not processing files on different branches than `main`. Do you?

**Comment by wm75** [comment]
image

so this should be doing the right thing.

Would be nice if we could prefill the text with the template content.

**Comment by arash77** [comment]
@bgruening @wm75 
Thank you I got it.
For template content should we create a git hook file?

**Comment by arash77** [comment]
By adding this to the end of the URL we can have a template for that file:
`&value=---%0Amedia%3A%0A%20 - bluesky%0A%20 - mastodon%0A%20 - matrix%0A%20 - slack%0A%0Aimages%3A%0A%20 - url%3A https%3A%2F%2Fexample.com%2Fa.jpg%0A%20%20%20 alt_text%3A A%0A%20 - url%3A https%3A%2F%2Fexample.org%2Fb.png%0A%20%20%20 alt_text%3A B%0A%0Amentions%3A%0A%20 bluesky%3A%0A%20%20%20 - a.bsky.social%0A%20 mastodon%3A%0A%20%20%20 - a%0A%20 matrix%3A%0A%20%20%20 - a%3Amatrix.org%0A%0Ahashtags%3A%0A%20 bluesky%3A%0A%20%20%20 - a%0A%20%20%20 - b%0A%20 mastodon%3A%0A%20%20%20 - c%0A%20%20%20 - d%0A---%0AYour text content goes here.`

**Review by arash77 — APPROVED** [review]
by adding this at the end of the URL it will

**Pull request merged**
